package SIGPROD2.GUI;

import SIGPROD2.Auxiliar.Erro;
import SIGPROD2.Auxiliar.Mensagem;
import SIGPROD2.BD.DadosConexao;
import SIGPROD2.BD.DadosConexaoException;

/**
 * Classe responsável por mostrar e gerenciar uma janela de configuração do
 * Banco de Dados.
 *
 * @author Rafael Casa
 * @version 22/03/2016
 */
public class GUI_BD_Config extends javax.swing.JFrame {

    /**
     * Método responsável por construír uma janela de configuração do Banco de
     * Dados.
     */
    public GUI_BD_Config() {
        initComponents();
        colocarInformacoesSalvas();
    }

    /**
     * Método responsável por verificar a existência de dados de conexão ao
     * banco de dados salvos anteriormente e colocar estes dados como valores
     * iniciais da tela.
     */
    private void colocarInformacoesSalvas() {
        try {
            DadosConexao dados = DadosConexao.getDadosConexaoSalvos();
            String usuario = dados.getUsuario();
            String senha = dados.getSenha();
            String ip = dados.getIp();
            String porta = dados.getPorta();
            String nomeBanco = dados.getNomeBanco();
            
            this.campoUser.setText(usuario);
            this.campoIp.setText(ip);
            this.campoNomeBanco.setText(nomeBanco);
            this.campoPorta.setText(porta);
            this.campoSenha.setText(senha);
        } catch (DadosConexaoException ex) {
            //Não há dados de conexão anteriores para mostrar
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoIp = new javax.swing.JTextField();
        campoPorta = new javax.swing.JTextField();
        campoUser = new javax.swing.JTextField();
        campoNomeBanco = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoSave = new javax.swing.JButton();
        botaoClear = new javax.swing.JButton();
        botaoClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ip:");

        jLabel2.setText("Porta:");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Nome do Banco:");

        botaoSave.setText("Salvar");
        botaoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSaveActionPerformed(evt);
            }
        });

        botaoClear.setText("Limpar");
        botaoClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClearActionPerformed(evt);
            }
        });

        botaoClose.setText("Fechar");
        botaoClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(campoPorta)
                            .addComponent(campoIp)
                            .addComponent(campoNomeBanco)
                            .addComponent(campoSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSave)
                        .addGap(18, 18, 18)
                        .addComponent(botaoClear)
                        .addGap(18, 18, 18)
                        .addComponent(botaoClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSave)
                    .addComponent(botaoClear)
                    .addComponent(botaoClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método chamado ao clique do botão fechar. Responsável por fechar essa
     * janela.
     *
     * @param evt O evento ocorrido.
     */
    private void botaoCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCloseActionPerformed

    /**
     * Método responsável por limpar todos os campos dessa janela.
     *
     * @param evt O evento ocorrido.
     */
    private void botaoClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClearActionPerformed
        this.campoIp.setText("");
        this.campoPorta.setText("");
        this.campoNomeBanco.setText("");
        this.campoUser.setText("");
        this.campoSenha.setText("");
    }//GEN-LAST:event_botaoClearActionPerformed

    /**
     * Método responsável por salvar as informações do Banco de Dados em um
     * arquivo, para futura utilização.
     *
     * @param evt O evento ocorrido.
     */
    private void botaoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSaveActionPerformed
        String nomeBanco = this.campoNomeBanco.getText();
        String usuario = this.campoUser.getText();
        char[] senhaVetor = this.campoSenha.getPassword();
        String senha = String.valueOf(senhaVetor);
        String ip = this.campoIp.getText();
        String porta = this.campoPorta.getText();
        DadosConexao dados = new DadosConexao(nomeBanco, ip, porta, usuario, senha);

        try {
            dados.salvar();
            Mensagem.mostraMensagemSucesso(this);
        } catch (DadosConexaoException ex) {
            Erro.entradaInvalida(this);
        }
    }//GEN-LAST:event_botaoSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BD_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BD_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BD_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BD_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BD_Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoClear;
    private javax.swing.JButton botaoClose;
    private javax.swing.JButton botaoSave;
    private javax.swing.JTextField campoIp;
    private javax.swing.JTextField campoNomeBanco;
    private javax.swing.JTextField campoPorta;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
